#!/bin/sh
VERSION=0.0.2
DISTRO=`lsb_release -sc`
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
set -e

# create debian source package
python setup.py sdist
rm -rf ~/build-edupython
mkdir ~/build-edupython
cp dist/edupython-$VERSION.tar.gz ~/build-edupython/edupython_$VERSION~$DISTRO.orig.tar.gz
cd ~/build-edupython
tar xvf edupython_$VERSION~$DISTRO.orig.tar.gz
cp -a $SCRIPTPATH/debian-$DISTRO ~/build-edupython/edupython-$VERSION/debian

# build .deb file
cd ~/build-edupython/edupython-$VERSION
debuild -us -uc

# copy debian source package and binary package to the dist/ directory
cp ~/build-edupython/python*deb $SCRIPTPATH/dist
cp ~/build-edupython/edupython_$VERSION~$DISTRO.orig.tar.gz $SCRIPTPATH/dist
cp ~/build-edupython/edupython_$VERSION~$DISTRO*.dsc $SCRIPTPATH/dist
cp ~/build-edupython/edupython_$VERSION~$DISTRO*.debian.tar.* $SCRIPTPATH/dist
rm -rf ~/build-edupython
